#!/system/bin/sh


SCRIPTNAME=cmd_tts_engines
show_usage () {
    echo "Usage: $SCRIPTNAME"
    echo "Get information about the available text-to-speech (TTS) engines. The name of an engine may be given to the cmd_text_to_speech command using the -e option."
    exit 0
}

while getopts :h option
do
    case "$option" in
	h) show_usage;;
	?) echo "$SCRIPTNAME: illegal option -$OPTARG"; exit 1;
    esac
done
shift $(($OPTIND-1))

if [ $# != 0 ]; then echo "$SCRIPTNAME: too many arguments"; exit 1; fi
/data/data/apotee.sky.poc1/files/bin/adbshellkit-api cmd_text_to_speech --es engine LIST_AVAILABLE

