#!/system/bin/sh

API=`getprop ro.build.version.sdk`
ABI=`getprop ro.product.cpu.abi | cut -c-3`
ABI2=`getprop ro.product.cpu.abi2 | cut -c-3`
ABILONG=`getprop ro.product.cpu.abi`
ARCH=arm
IS64BIT=false
if [ "$ABI" = "x86" ]; then ARCH=x86; fi;
if [ "$ABI2" = "x86" ]; then ARCH=x86; fi;
if [ "$ABILONG" = "arm64-v8a" ]; then ARCH=arm64; IS64BIT=true; fi;
if [ "$ABILONG" = "x86_64" ]; then ARCH=x64; IS64BIT=true; fi;

# Sets paths to binaries and libs based off detected architecture
case $ARCH in
  arm)
    export PATH="$PATH:/data/data/net.kwatts.android.droidcommandpro/files/bin.arm"
    export DIR_TOOLS="/data/data/net.kwatts.android.droidcommandpro/files/bin.arm"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/data/data/net.kwatts.android.droidcommandpro/files/lib.arm"
    ;;
  arm64)
    export PATH="$PATH:/data/data/net.kwatts.android.droidcommandpro/files/bin.aarch64"
    export DIR_TOOLS="/data/data/net.kwatts.android.droidcommandpro/files/bin.aarch64"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/data/data/net.kwatts.android.droidcommandpro/files/lib.aarch64"
    ;;
  x86)
    export PATH="$PATH:/data/data/net.kwatts.android.droidcommandpro/files/bin.x86"
    export DIR_TOOLS="/data/data/net.kwatts.android.droidcommandpro/files/bin.x86"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/data/data/net.kwatts.android.droidcommandpro/files/lib.x86"
    ;;
  x86_64)
    export PATH="$PATH:/data/data/net.kwatts.android.droidcommandpro/files/bin.x86_64"
    export DIR_TOOLS="/data/data/net.kwatts.android.droidcommandpro/files/bin.x86_64"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/data/data/net.kwatts.android.droidcommandpro/files/lib.x86_64"
    ;;
esac

# Global paths
export PATH="$PATH:/data/data/net.kwatts.android.droidcommandpro/files/scripts"
export PREFIX='/data/data/net.kwatts.android.droidcommandpro/files'
export HOME='/data/data/net.kwatts.android.droidcommandpro/files/home'
export LANG='en_US.UTF-8'
export SHELL='/system/bin/sh'
# Need to remove this and DIR_TOOLS from commands as it's not used anymore
export DIR_SCRIPTS="/data/data/net.kwatts.android.droidcommandpro/files/scripts"

# Global helper functions
function kill_adbshellkit_processes {
    ADBSHELLUID=`ps -ef | grep kwatts | grep -v grep | cut -F 1`
    for p in `grep $ADBSHELLUID | grep -v grep | grep -v net.kwatts.android.droidcommandpro | cut -F 2`
    do
        kill $p
    done
}
