#!/system/bin/sh
#
# References:
# - https://infosecravindra.github.io/cheatsheets/termux-cheat-sheet.html
#
# On host computer run:
# PKGUID=`adb shell stat -c %U /data/data/apotee.sky.poc1`
# adb shell "su -l $PKGUID -c /data/data/apotee.sky.poc1/files/bin/adbshell"
# adbshellkit cmd_device_dump | jq -r '(map(keys_unsorted) | add | unique) as $cols | $cols, map(. as $row | $cols | map($row[.]))[] | @csv'
# adbshellkit cmd_device_dump | jq '.. | keys? | flatten[] | strings'

source /data/data/apotee.sky.poc1/files/home/bashrc
cd "$HOME"
exec "$SHELL" -l
